// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXQfn7WVvLMneDCDJSMQs-U-ichhg0ubM',
    appId: '1:404747200571:web:a8e9a8664ba36aa28a141e',
    messagingSenderId: '404747200571',
    projectId: 'demoapplication-398f5',
    authDomain: 'demoapplication-398f5.firebaseapp.com',
    databaseURL: 'https://demoapplication-398f5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'demoapplication-398f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3QXHEtNQYtOF8PyMTSOPK03WEJzWJDlg',
    appId: '1:404747200571:android:766a0af8637c76048a141e',
    messagingSenderId: '404747200571',
    projectId: 'demoapplication-398f5',
    databaseURL: 'https://demoapplication-398f5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'demoapplication-398f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNkIKMjCV_xWN6aavhf5TDdQIz9aAaLWU',
    appId: '1:404747200571:ios:f6d1c11470b1ae208a141e',
    messagingSenderId: '404747200571',
    projectId: 'demoapplication-398f5',
    databaseURL: 'https://demoapplication-398f5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'demoapplication-398f5.appspot.com',
    iosBundleId: 'com.example.listviewwidget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNkIKMjCV_xWN6aavhf5TDdQIz9aAaLWU',
    appId: '1:404747200571:ios:13941bb592d236e38a141e',
    messagingSenderId: '404747200571',
    projectId: 'demoapplication-398f5',
    databaseURL: 'https://demoapplication-398f5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'demoapplication-398f5.appspot.com',
    iosBundleId: 'com.example.listviewwidget.RunnerTests',
  );
}
